field.formatter.settings.hierarchical_term_formatter:
  type: mapping
  label: 'Hierarchical Term Formatter settings'
  mapping:
    display:
      type: string
      label: 'Whether to display all elements or a specified amount'
    link:
      type: boolean
      label: 'Whether the terms should link to the entity'
    wrap:
      type: string
      label: 'The HTML structure to wrap elements'
    separator:
      type: string
      label: 'The string that should separate each term'
    reverse:
      type: boolean
      label: 'Whether display order should be in descendant fashion'
